<?php

namespace AbmmHasan\OTP;

class TOTP
{
    use Common;


    /**
     * Initializes a new instance of the class.
     *
     * @param string $secret The secret key.
     * @param int $digitCount The number of digits in the generated code. Default is 6.
     * @param int $interval The time interval in seconds. Default is 30.
     */
    public function __construct(
        string $secret,
        int $digitCount = 6,
        int $interval = 30
    ) {
        $this->secret = $secret;
        $this->digitCount = $digitCount;
        $this->period = $interval;
    }

    /**
     * Generates a one-time password (OTP) based on the given timestamp (or Current Timestamp).
     *
     * @param int|null $input The input value used to generate the OTP. If null, the current timestamp is used.
     * @return string The generated OTP.
     */
    public function getOTP(int $input = null): string
    {
        return $this->getPassword($input ?? time());
    }

    /**
     * Verifies if the given OTP matches the OTP generated by the given timestamp (or Current Timestamp).
     *
     * @param string $otp The OTP to be verified.
     * @param int|null $input The input used to generate the OTP. Defaults to Current Timestamp.
     * @return bool Returns true if the OTP matches the generated one, otherwise false.
     */
    public function verify(string $otp, int $input = null): bool
    {
        return hash_equals($otp, $this->getOTP($input));
    }
}
